### ISSUE TITLE
Clicking Alt Text Helper Button Triggers Lightbox

### ISSUE THREAD

**Issue by captainharrie** [boscoxvi/npfphotosets#1]
Last week, [tumblr implemented a button for showing alt text on NPF images](https://changes.tumblr.com/post/685426330509180928/friday-may-27th-2022).

Single images which are not lightboxed work just fine:
![gif showing the intended behaviour](https://i.imgur.com/LG2bnLV.gif)

But when images are lightboxed, clicking the alt text helper also triggers the lightbox:
![gif showing the lightbox activating when clicking the alt text helper](https://i.imgur.com/PSDIQCR.gif)

**Comment by boscoxvi** [comment]
Hi and thank you so much for reporting on this! I've been so busy I would probably miss on this update for a good bit. I won't be able to work on it right away but I hope to take a look at it at least by the end of this week; hopefully it's simple enough. Thanks again!!

**Comment by boscoxvi** [comment]
Should be fixed now; later than I wanted it to, but here it is. Do tell if it persists! I will keep an eye on it, though! :D
